version: 1
services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn DevTest.wsgi
    env:
      DJANGO_SETTINGS_MODULE: DevTest.settings
